### ISSUE TITLE
NEW DISCORD SERVER https://lunanom.hackergavin.repl.co/service/hvtrs8%2F-dksaopd%2Ccmm-cjalnglq%2F%3B85544547235113852-9%3A7766765017331%3A77

### ISSUE THREAD

**Issue by Hankypoo7** [Hankypoo7/The-blooket-hacks#140]
https://lunanom.hackergavin.repl.co/service/hvtrs8%2F-dksaopd%2Ccmm-cjalnglq%2F%3B85544547235113852-9%3A7766765017331%3A77
join if you like :)

**Comment by VillainsRule4000** [comment]
I don't have Discord. Could we use another platform?

**Comment by VillainsRule4000** [comment]
I use guilded.gg, which is actually a Discord copy, but has 10x the features...
