### ISSUE TITLE
my work

### ISSUE THREAD

**Issue by GooseterV** [Hankypoo7/The-blooket-hacks#143]
I'd appreciate if you take down all of my scripts from your own blooket repository. If you're going to have them, at least put them in a fork but i really do not like it whe peope steal my work and post it as their own. If you add a section that specifically states everything in it was made by me, i'd accept it but right now you've only labelled 2 of every single script you stole from me as "mine" when realistically, i made all of them.

**Comment by GooseterV** [comment]
thank you for removing it, you don't know how annoying it is when people post other people's work

**Comment by GooseterV** [comment]
also, if you wanted to check the state of my stuff be sure to read the top of the readme file of my repo

**Comment by VillainsRule4000** [comment]
@GooseterV Good to know! Some devs are fine as long as it is credited. We have all credits in the Wiki. This is mostly a hack compilation, really.
