### ISSUE TITLE
[Github] Formatting Error

### ISSUE THREAD

**Issue by VillainsRule4000** [Hankypoo7/The-blooket-hacks#168]
According to file/directory name guidelines...
1. No directory or file name should contain spaces, as this confuses the system. 
      - Files names may be formatted such as `My-File.txt`, `MyFile.txt`, or `myFile.txt`.
      - These are not the only options.
 2. Files should have a name ending.
       - For example, `myFile` is not a valid name as it does not have an ending. For plain text, `.txt` is a good ending. For info, `.md` is a good ending.

Also it's quite funny you're being skids off gliz. Just code them.
Also, requesting you removed or entirely rewrite the `Possibilities of scripts` section in your `README.md` file.

I have made several scripts and added them to my `BlooketMaster` repository. This is a warning that you do not have rights to use any of these scripts. Scripts in the `hacks` directory without the Gliz footer were made by me.

**Comment by v8f** [comment]
they arent being _"skids"_ off of _gliz_, they _credited him_ and they also _credited other people who had helped with this_. also.. this project actually have multiple people that were helping here that could kind of code including me? look.. we arent trying to steal anything from you :skull: i dont get why ur still babbling about this, just mind your own business and go away and never come back

**Comment by VillainsRule4000** [comment]
Fixed in commit 86e902201ebaf1f528ce810ddd0ceeacbcca1d4b.
