### ISSUE TITLE
[SCRIPT DOWN]

### ISSUE THREAD

**Issue by ghost** [Hankypoo7/The-blooket-hacks#175]
**BASIC INFO**
Gamemode: Global
Script Name: AddTokensXP

**TROUBLESHOOTING**
Is this the first script you used on the page? (yes)

**DEVICE INFO**
Browser (Safari): 
Device (Ipad):

**EXTRA**
I think you could make bookmark codes

**Comment by Hankypoo7** [comment]
thank you, we will work on a fix

**Comment by 123345666777777777777777777777777** [comment]
Use this to convert https://caiorss.github.io/bookmarklet-maker/

**Comment by VillainsRule4000** [comment]
Schoolcheats expires after 24hrs. Stop using SC.

**Comment by Jude-Gideon** [comment]
@VillainsRule4000 This is really late but you can make SC not expire.

**Comment by VillainsRule4000** [comment]
@Jude-Gideon idc about this anymore
