### ISSUE TITLE
expiration

### ISSUE THREAD

**Issue by vantr-o** [Hankypoo7/The-blooket-hacks#177]
I've been looking into this API for a while, the hacks coming from school cheats expire after 24 hrs. Might want to change those.

**Comment by VillainsRule4000** [comment]
This is correct. Honestly, I think I'm the only collab who can properly code. My repo [@VillainsRule4000/BlooketMaster](https://github.com/VillainsRule4000/BlooketMaster/tree/main/hacks) should have working scripts.

**Comment by vantr-o** [comment]
> 

I can add scripts without footers, no obscuration, and ones that work if you'd like.

**Comment by VillainsRule4000** [comment]
This repo is kinda dead :skull:

**Comment by vantr-o** [comment]
> This repo is kinda dead 💀

yeah, when gliz returned it died off.
