### ISSUE TITLE
[SCRIPT DOWN]

### ISSUE THREAD

**Issue by Reloadandtryagain** [Hankypoo7/The-blooket-hacks#187]
Could you maybe create one to spam open boxes?
Gamemode: Normal
Script Name: I don't know

**TROUBLESHOOTING**
Is this the first script you used on the page? (y/n) N
Did the Console show any issues? (if you have access) (y/n) N I don't have acess

**DEVICE INFO**
Browser (eg Chrome):  Chromebook
Device (eg smartphone): None. I don't have a phone

**EXTRA**
Type anything additional below!
If you know 3kh0 he can help. He is pretty good at coding and i use many of his codes. (Mostly Bookmarklets or websites)

**Comment by Hankypoo7** [comment]
I can try, some scripts arent possible sadly, but ill igve it a shot

**Comment by Hankypoo7** [comment]
done
