### ISSUE TITLE
Staff???

### ISSUE THREAD

**Issue by CPScript** [Hankypoo7/The-blooket-hacks#191]
hello, i would like to know if your still hiring?

**Comment by Hankypoo7** [comment]
Yes, you can check out the google form here:
https://forms.gle/Qt7tGSw4WAEzuVPs8

**Comment by CPScript** [comment]
done

**Comment by Hankypoo7** [comment]
I accepted you, please dont abuse powers and welcome!

**Comment by CPScript** [comment]
ok, thanks

**Comment by Hankypoo7** [comment]
yep, thank you

**Comment by CPScript** [comment]
oh... by the way, i know how to use javascript and i do make things pretty, im just not the best at using it atm (i haven't for a while now)

**Comment by Hankypoo7** [comment]
ok thats fine
