### ISSUE TITLE
Change

### ISSUE THREAD

**Issue by CPScript** [Hankypoo7/The-blooket-hacks#194]
I know you say not to change the read me but... it doesn't look so good, try this.

<div align="center"> 
  <h1>Welcome...</h1>
  <p>
    Enjoy all of the Hacks👍
  </p>
  <br>
  <br>
  <br>
  <h2>Credits</h2>
<details open>
<summary>Credits to</summary>
<br>
  
  <ul>
    <li><a href="https://github.com/therealgliz/blooket-hacks">glixzzy</a></li>
    <li><a href="https://github.com/qaiik/blkt-reader">qaiik</a></li>
    <li><a href="https://github.com/rxzyx/Blooket-Hacks">rxzyx</a></li>
    <li><a href="https://github.com/cph101/Blooket-Hacks">cph101</a></li>
    
  <p>Thanks to all of you for helping make this possible! ❤️</p>
  </ul>
</details>

  <br>
  <br>
  <br>
  <h2>Issues??? | Contact Us</h2>
  <p>Is there somthing wrong? make an issue and we will check it out for you, For less important things, move to the Discussions to avoid clutter.</p>
  <br>
  <br>
  <br>
  <h2>=======How to use=======</h2>
  
  <p>For info on how to use each script, visit the <b><a href="https://github.com/Hankypoo7/The-blooket-hacks/wiki">wiki</a></b>.</p>
  <br>
  <br>
  <br>
  <h2>Possibilities of scripts</h2>
  
  <p>
    I have have seen a lot of people talk about how someone should make something that is more than adding 500+ tokens.<br>
    We can not do that due to the Blooket API. The token limit is defined by the API, meaning adding 501 tokens would just ban your account.<br>
    There are some things you can't change without owning that website or having access to the database of the website.<br>
    A couple more examples of impossible scripts are changing box costs and adding all Blooks permanently. Please keep this in mind before asking for a script.<br>
  </p>
</div>

**Comment by Hankypoo7** [comment]
you can change it if you want :)

**Comment by CPScript** [comment]
ok
