### ISSUE TITLE
Fix Credits 🖋️

### ISSUE THREAD

**Issue by CrazyH2** [Hankypoo7/The-blooket-hacks#196]
Please make the credits correct by add myself to the list as i made the blooket hacks with cph101

**Comment by CrazyH2** [comment]
Its not like i am asking for you to take it down

**Comment by CrazyH2** [comment]
Remove our hacks then

**Comment by CrazyH2** [comment]
This is our license:

HCPL Private License (Version 1.0)
© Copyright 2022 cph101 & CrazyH

Usage of this license implies that any person obtaining a copy of this software and associated documentation
files (the “Software”), to use and produce files using this Software. They may not; copy modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software.

The above copyright notice and this permission notice shall be included in all copies or substantial portions
of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.

**Comment by CrazyH2** [comment]
And your license goes against all of ours so its an easy way to bypass our license so please remove our hacks off here! And you could even replace them with minesrafts if they are so simular

**Comment by cph101** [comment]
Agreed

**Comment by Minesraft2** [comment]
man is fighting for his life in here

**Comment by src-ry** [comment]
> And your license goes against all of ours so its an easy way to bypass our license so please remove our hacks off here! And you could even replace them with minesrafts if they are so simular

\>skids off of Minesraft2
\>adds basic features to it
\>makes their own private license 
\>complains to a blooket hack repo because they are violating their license
you my good friend, are the ultimate skid

**Comment by CPScript** [comment]
omfg this issue s so stupid, just remove his hacks and get over with it...

**Comment by CPScript** [comment]
> no wonder such a retard could only work at a skidding blooket hacks repo 🤣 what a retard

"could only work at"
Huh? this isn't a job dumbass... Im finna start fixing your sentences.

**Comment by CPScript** [comment]
💀 imagine only getting 100+ visitors on a repo... But still, good for you! 👍🏼

**Comment by CPScript** [comment]
> it's sad my proxy can't load images

Your proxy should load images, unless you're using a very shitty one.

**Comment by CPScript** [comment]
> im sure your skidded shit gets more. at least i got the talent to make stuff for myself 👯‍♀️

You're not better than anyone else🤣
A lot of your repos are Forks, and are the same... they all have to do with the same shit "blooket & school cheats"... NGL you should actually make something good... and you use a proxy to go onto GitHub??????????? smh 🤣 🤣 🤣

**Comment by CPScript** [comment]
> Please make the credits correct by add myself to the list as i made the blooket hacks with cph101

ill add you to the credits 🙃

**Comment by src-ry** [comment]
> > im sure your skidded shit gets more. at least i got the talent to make stuff for myself 👯‍♀️
> 
> You're not better than anyone else🤣
> A lot of your repos are Forks, and are the same... they all have to do with the same shit "blooket & school cheats"... NGL you should actually make something good... and you use a proxy to go onto GitHub??????????? smh 🤣 🤣 🤣 
> 

its official, you no longer can use a proxy on github

**Comment by Hankypoo7** [comment]
@VillainsRule use your fucking brain. this is blooket hacks and yall are arguing about "who stole what". stupid ass middle school beef. you dont have shit to do shit ill counter everything your sorry ass says
